### ISSUE TITLE
 portrait or landscape video

### ISSUE THREAD

**Issue by sugizo** [beltoforion/stellarium-to-video#10]
**objective**
create vertical (portrait) video

**ffmpeg command**
```
ffmpeg -h

-s size             set frame size (WxH or abbreviation)
```

**kalstar.py**
`'-s', '1920x1080',`
try to change into
`'-s', '1080x1920',`

**result**
still get the horizontal (landscape) video

**expected result** 
get the vertical (portrait) video

**suggestion** 
nice to have video w x h parameter so that user can create vertical or horizontal video

best regards

**Comment by beltoforion** [comment]
This feature would require to start stellarium in windowed mode or bring it into windows mode post start. Stellarium would need to provide a way to control this which it does not. Since that functionality is not supported by stellarium i cannot do anything within the bounds of a reasonable implementation.

**Comment by beltoforion** [comment]
I reopened the issue. It might actually be a good idea to have such a feature although I'm not sure how to make this happen at the moment. Portrait orientation would be much better suited for distributing videos over social media channels aimed at smartphones.

**Comment by sugizo** [comment]
you got that right in purpose to publish it on ig, tiktok or utube short, 
currently solve it with moviepy
**e.g.**
```
pip install -U moviepy
from moviepy.editor import VideoFileClip
video_clip = VideoFileClip("kalstar_stellarium_without_audio.mp4")

# edtv vertical = 720 x 576
# hd vertical = 1920 x 1080
# 4k vertical = 3840 x 2160
# 8k vertical = 7680 x 4320
height = 3840
width = 2160

video_resized = video_clip.resize(height = height)

video_croped = video_resized.crop(x_center = height / 2, # or width / 2, depend on the resolution choice
                                  y_center = height / 2,
                                  width = width, height = height)

video_croped .write_videofile('ig.mp4', fps = 60)
```

the problem here is 
crop generated video focus on the center, 
so 
above code remove the label information 
about place 
and 
date time 
on video, 

perhaps you have better idea 
how to put information label about place and date time in portrait video

thanks and best regards

**Comment by beltoforion** [comment]
In general there is a way to start stellarium in windowed mode and use a resolution that is portrait mode. However there is one big drawback. Stellarium will not let me create a window whose size exceeds the screen resolution. Therefore any portrait mode window would be limited to 1080 pixel height on a 1920x1080 display.  Would that even be usefull for your video?

**Comment by beltoforion** [comment]
I can probably fix it. But it will probably only work with GNOME and possibly on windows if you want Full-HD vertical video. Here is an example:

https://github.com/beltoforion/stellarium-to-video/assets/2202567/baee9422-7594-4fc3-a7c0-fe4562d6a518

I will see wether i can make it work on windows too and then push the modification to the master branch.

**Comment by sugizo** [comment]
great, thanks

usually re processing again all of kalstar output video (resize to 4k, and add sound)
before upload to soc med
so it doesnet matter, whatever video shape (w, h) kalstar generated

suggestion for windows user, 
just use it on wsl (windows subsidiary linux)
then you free to go from windows users

best regards

**Comment by beltoforion** [comment]
It is implemented. Use the -wsz 1080x1920 option (stellarium window size)  in combination with -sz 1080x1920 (mpeg video resolution)
