### ISSUE TITLE
no video generated

### ISSUE THREAD

**Issue by sugizo** [beltoforion/stellarium-to-video#21]
**env**
wsl debian (windows subsidiary linux)

**execute**
```
python3 /mnt/c/stellarium-to-video/stellarium-to-video.py \
-ts P6M -dt P1D -o "/mnt/c/Users/sugizo/Downloads/vertical.mp4" \
-t /mnt/c/stellarium-to-video/script/planet_track.ssc \
-sz 1080x1920 -wsz 1080x1920 \
-v 180,30,70 \
-d 1961-10-08T12:00:00+01:00 \
-l Freiberg -c "Dance of Planets"
```

**log tail (trying paste full log but hv browser stuck)**
```
INFO Saving screenshot in file:  "/tmp/kalstar_frames/frame_183.png"
INFO Saving screenshot in file:  "/tmp/kalstar_frames/final.png"
Unloaded plugin "SolarSystemEditor"
Unloaded plugin "Satellites"
Unloaded plugin "Oculars"
Unloaded plugin "Novae"
Unloaded plugin "MeteorShowers"
Unloaded plugin "Exoplanets"
Downloaded 1 files (0 kbytes) in a session of 607.684 sec (average of 0 kB/s + 1 files from cache (13 kB)).
LandscapeMgr: Clearing cache of 0 landscapes totalling about  0 MB.
StelGLWidget destroyed
```

**result**
no video generated in /mnt/c/Users/sugizo/Downloads/ folder

**expected result**
have video generated in /mnt/c/Users/sugizo/Downloads/vertical.mp4

best regards

**Comment by sugizo** [comment]
spot the problem on the first posted, 
as it run on linux (debian), 
so the wsz parameter should not ignored

**problem shell execute on linux**
`-sz 1080x1920 -wsz 1080x1920 \`

**suggestion**
have a conditional os check environment, 
```
if on *nix env (linux, mac, etc): 
    then ignore -wsz parameter
```

best regards

**Comment by beltoforion** [comment]
The wsz option should never been ignored when given. It is different from -sz. -sz is the resolution of the output video created by ffmpeg. -wsz defines the physical size of the stellarium window. -wsz only works with Windows and Linux + GNOME desktop manager. What Desktop manager did you use?

**Comment by sugizo** [comment]
not sure about what desktop manager is used 
by wsl (windows subsidiary linux)

always execute on command prompt windows (from this go to wsl > then execute stelarium-to-video,py command which is on debian linux env), 
but 
can open stellarium and vlc 
which install on debian wsl 
from windows

**Comment by beltoforion** [comment]
Sorry but that is not gonna work. 

Under WSL the script thinks it is running under linux, because technically it is. But you are executing the windows version of Stellarium. The script then tries to change the stellarium window size in a way that only works on Linux. That cannot work! If you want to execute the script under windows you should execute the python script from the windows terminal.  Alternatively you can install an X11 server,  then compile run the linux version of stellarium under windows. But i don't even know if that would work at all.

**Comment by beltoforion** [comment]
I have filed this as #26; There is a chance that there is a workaround
