### ISSUE TITLE
video output generated but it automatcally open vlc (without -s parameter)

### ISSUE THREAD

**Issue by sugizo** [beltoforion/stellarium-to-video#23]
**env**
wsl debian (windows subsidiary linux)

**prerequisites**
```
sudo apt update
sudo apt install -y python3-skyfield python3-isodate python3-geopy stellarium ffmpeg
```

**execute**
```
python3 /mnt/c/stellarium-to-video/stellarium-to-video.py \
-ts P1Y -dt P2D -o /mnt/c/Users/sugizo/Downloads/output.mp4 \
-t /mnt/c/stellarium-to-video/script/suntrack.ssc \
-d 2024-06-20T12:00:00+01:00 \
-l Freiberg -c Analemma
```

**result**
video output generated but it automatcally open vlc, 
as you can see the execute code not include -s parameter

**expected result**
video generated not automatically open vlc, 
because no -s parameter on the execute code

best regards

**Comment by beltoforion** [comment]
fixed
