### ISSUE TITLE
fps parameters like on kalstar.py before

### ISSUE THREAD

**Issue by sugizo** [beltoforion/stellarium-to-video#25]
**objective** 
can set fps on output video

**solution**
pass the fps argument 
like on kalstar.py 
then pass it 
to ffmpeg command -r argument
**e.g.**
`ffmpeg -r 60`

**expected result, p60 indicates, fps is set to 60**
![image](https://github.com/beltoforion/stellarium-to-video/assets/2418295/495ac481-7cec-478a-a3e2-c2b45eba24ca)

best regards

**Comment by beltoforion** [comment]
There is a -fps argument. It did not change.
